
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: folio
    password: folio
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8888
